# ------------------------------------------------------------------------
# Rules for STI project
# ------------------------------------------------------------------------

SecRule TX:PARANOIA_LEVEL "@lt 1" "phase:1,id:942011001,nolog,pass,skipAfter:END-STI_PROJECT_RULES"
SecRule TX:PARANOIA_LEVEL "@lt 1" "phase:2,id:942012001,nolog,pass,skipAfter:END-STI_PROJECT_RULES"


# Rules list

SecRule REQUEST_URI "/ftp/legal.md" " id:102, allow"
SecRule REQUEST_URI "/ftp/order" " id:104, allow"
SecRule REQUEST_URI "/ftp/" " id:101, deny"

#SecRule REQUEST_URI|ARGS|REQUEST_BODY "true" "phase:2, id:103, deny"



#Rules list end


SecMarker "END-STI_PROJECT_RULES"
